RESTIC_PASSWORD: ENC[AES256_GCM,data:gXDVNpdBVUVDuvkd636urAzlOiR9LGq/dPQgfgvlQEquRbpUmh900C+zHDQ=,iv:forT51pjIfv8q+WIAYDAZQpxJMNUfHRXLrUue+3qIgk=,tag:87QcgYhPyBt0x1Y80undww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bHNSRUJqVklXc0FNY01q
            Tnc5aVg4RWszbjMvR2pwS3NBTDRBSWpoTUQ4CktyUDg5WHlaMkNxMU1KL3FCUUhm
            cG9MdTIxWDYrNmQ4cTh0dVJTL2pOckUKLS0tIFNJVmhpRDY4VHVFY0VNOFlEbHF2
            M2ViUWtJQmNGa1ljTmJiSG5mb3V6WDAK3amW5TLBkAKjuewICb/3ZtjgAShWqS2p
            C0NZJbNjG7eGvAK4dWL972EBkPHzjqHskfJKV52PZTCkskn7MR5unw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12xae728xxd5egtmx5f6r4fakqswcg3xkswzn9y290tl0yve4nsnsfm7rkd
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4anJhbGl0TnBhY0pnNGV3
            SmZTa0tHa2txU1hSMEcxalBEc1NwOHpUQkdvCmorclltTTlQNmsvZHE1UWxETkEw
            cWZ6V0N5dHE0K0Nid2xCMThGTGpOSEkKLS0tIHpOS3JIYkFQVWJNOW1IVzNkcm5M
            UjlWMFVhNW5IWnNReE1ZcU5oVnpkanMK8hAXmcfnUhkZlcnrYyyobGBXgNFePSQN
            wTa31L0h1fuil5ZTr9oFj/UegfaAGaC5UnxmaXj1eeW9cPLP0q2vVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ef9nfnekwe3fkx05qz96hyqzeznvuwd22h7sshazgtm9tldt0eyqmpvgu7
    lastmodified: "2026-09-30T05:23:09Z"
    mac: ENC[AES256_GCM,data:op/d08Iqq8u70Yaw/AARahWEa6Q2z9dbWbbLrLtpz317Iir5tLTrQMZBgUVwydpiH0uUtE8pQGnnoJmCN3+kK3cJJ1FOkdpwlHbhnEYXIH8tRtiOYaisgKiV3sJZTqKS9ttXlNtwXMMfF9XIUi22DNgBjy43aisXYh+VsGAh41M=,iv:y5qu6//YeEEzv1zgqvkfA0s56mQSYPwrLMiJOE1PAOc=,tag:H/nnjX2F3O2Dcg09nRlUjw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
