creation_rules:
  - path_regex: .*\.enc\.(env|ya?ml|json)$
    age: >-
      age15k2zqufxhmww5yjhxmzw5nrgccche5f0d5gj274lrr4dmenqvalsl6ewuy,
      age12puyn2xq56sdrkwpd0avf7rez6424z56cfzh4gy5xht267h30afsap4ljx
