services:
  mongo:
    image: mongo:8
    labels:
      komodo.skip:
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DATABASE_PASSWORD}
    networks: [db]

  core:
    image: ghcr.io/moghtech/komodo-core:2
    labels:
      komodo.skip:
    init: true
    restart: unless-stopped
    depends_on: [mongo]
    ports:
      - 127.0.0.1:9120:9120
    env_file: [compose.env, .env]
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
    volumes:
      - keys:/config/keys
      - /etc/komodo/backups:/backups
    networks:
      default:
      db:
      edge:
        aliases: [komodo-core]

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:2
    labels:
      komodo.skip:
    init: true
    restart: unless-stopped
    depends_on: [core]
    env_file: [compose.env, .env]
    volumes:
      - keys:/config/keys
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo
    networks: [default]

volumes:
  mongo-data:
  mongo-config:
  keys:

networks:
  default:
  db:
    internal: true
  edge:
    name: edge-komodo
