all:
  hosts:
    prestes-vps:
      ansible_host: prestes.cloud
      ansible_user: "{{ instance.admin_user }}"
      ansible_ssh_private_key_file: "{{ instance_config['keys']['ssh'] | expanduser }}"
