[[procedure]]
name = "deploy-on-push"
description = "Sincroniza os recursos e faz deploy em ordem: dados, aplicações, borda"

[[procedure.config.stage]]
name = "Sync"
executions = [
  { execution.type = "RunSync", execution.params.sync = "prestes-vps" },
]

[[procedure.config.stage]]
name = "Dados"
executions = [
  { execution.type = "BatchDeployStack", execution.params.pattern = "postgres, garage" },
]

[[procedure.config.stage]]
name = "Aplicações"
executions = [
  { execution.type = "BatchDeployStack", execution.params.pattern = "authentik" },
]

[[procedure.config.stage]]
name = "Borda"
executions = [
  { execution.type = "BatchDeployStack", execution.params.pattern = "caddy" },
]
