[[stack]]
name = "caddy"
[stack.config]
server = "prestes-vps"
repo = "AlexPrestes/prestes-vps"
branch = "main"
run_directory = "stacks/caddy"

[[stack]]
name = "postgres"
[stack.config]
server = "prestes-vps"
repo = "AlexPrestes/prestes-vps"
branch = "main"
run_directory = "stacks/postgres"
pre_deploy.command = "sh /etc/komodo/stacks/postgres/scripts/decrypt-secrets.sh /etc/komodo/stacks/postgres/stacks/postgres"

[[stack]]
name = "garage"
[stack.config]
server = "prestes-vps"
repo = "AlexPrestes/prestes-vps"
branch = "main"
run_directory = "stacks/garage"
pre_deploy.command = "sh /etc/komodo/stacks/garage/scripts/decrypt-secrets.sh /etc/komodo/stacks/garage/stacks/garage"

[[stack]]
name = "authentik"
[stack.config]
server = "prestes-vps"
repo = "AlexPrestes/prestes-vps"
branch = "main"
run_directory = "stacks/authentik"
pre_deploy.command = "sh /etc/komodo/stacks/authentik/scripts/decrypt-secrets.sh /etc/komodo/stacks/authentik/stacks/authentik 1000 && sh /etc/komodo/stacks/authentik/scripts/pg-provision.sh authentik /etc/komodo/stacks/authentik/stacks/authentik/.secrets/AUTHENTIK_DB_PASSWORD"
post_deploy.command = "sh /etc/komodo/stacks/authentik/scripts/authentik-set-admin.sh"
